<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9ac5cff7-a567-4679-9749-0d3ccfc75a90</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Shuttle.Hopper.AzureStorageQueues" Version="21.0.1-rc1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="21.0.1-rc1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="21.0.1-rc1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orders.Data\Orders.Data.csproj" />
    <ProjectReference Include="..\Orders.Messages\Orders.Messages.csproj" />
    <ProjectReference Include="..\Orders\Orders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
