<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>814df129-cfb5-4603-a818-08547896cefa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="21.0.1-beta" />
    <PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="21.0.1-beta" />
    <PackageReference Include="Terminal.Gui" Version="1.19.0" />
  </ItemGroup>

</Project>
