<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shuttle.Contract" Version="21.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Shuttle.Contract">
      <HintPath>C:\Users\me\.nuget\packages\Shuttle.contract\21.0.0\lib\net10.0\Shuttle.Contract.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
