CREATE TABLE [dbo].[Game](
	[Id] [uniqueidentifier] NOT NULL,
	[Bowler] [varchar](65) NOT NULL,
	[DateStarted] [datetime] NOT NULL,
 CONSTRAINT [PK_Game] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
