<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d47e3068-afa2-4c7f-9c24-14f8fc3f76db</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="21.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="21.0.1" />
    <PackageReference Include="Terminal.Gui" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\" />
  </ItemGroup>

</Project>
